[tool.pylint.MASTER]
ignore = ["venv", ".git"]
ignore-paths = ["^venv/.*$"]

[tool.pylint.MAIN]
# S'assurer que Pylint utilise le même interpréteur
extension-pkg-whitelist = ["pydantic"]

[tool.pylint.FORMAT]
max-line-length = 100

[tool.pylint.BASIC]
good-names = ["i", "j", "k", "ex", "Run", "_", "x", "y", "db", "id"]

[tool.pylint.DESIGN]
max-args = 5
max-attributes = 7